image: node:18

stages:
  - lint
  - build
  - deploy

before_script:
  - npm install pnpm@7.27.1 -g
  - pnpm install

type-check-job:
  stage: lint
  only:
    - master
  script:
    - pnpm type-check

lint-job:
  stage: lint
  only:
    - master
  script:
    - pnpm lint

build-job:
  stage: build
  only:
    - master
  script:
    - echo 'build success'

deploy-job:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - echo 'deploy success'
