image: node:18

stages:
  - lint

before_script:
  - npm install pnpm@7.27.1 -g
  - pnpm install

type-check-job:
  stage: lint
  only:
    - master
  script:
    - pnpm type-check

lint-job:
  stage: lint
  only:
    - master
  script:
    - pnpm lint
