name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm install pnpm -g
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: |
          pnpm type-check
